import os
import io
import pytest
from datetime import datetime
from unittest.mock import MagicMock


class DevelopmentState:
    def __init__(self, id, status, requirement, plan, database_code, backend_code, frontend_code, final_report):
        self.id = id
        self.status = status
        self.requirement = requirement
        self.plan = plan
        self.database_code = database_code
        self.backend_code = backend_code
        self.frontend_code = frontend_code
        self.final_report = final_report


def save_execution_log(state, log_dir="dist/logs", now_fn=None, base_dir=None, open_fn=open, makedirs_fn=os.makedirs):
    if now_fn is None:
        now_fn = datetime.now
    if base_dir is None:
        base_dir = os.getcwd()
    log_path = os.path.join(base_dir, log_dir)
    makedirs_fn(log_path, exist_ok=True)
    timestamp = now_fn().strftime("%Y%m%d_%H%M%S")
    log_file = os.path.join(log_path, f"execution_log_{timestamp}.md")
    log_content = f"""# Agentic Software Factory - Execution Log

**Generated:** {now_fn().strftime("%Y-%m-%d %H:%M:%S")}
**Flow ID:** {state.id}
**Status:** {state.status}

---

## Original Requirement

```
{state.requirement}
```

---

## PHASE 1: Planning Crew Output

### Technical Specification (Architect)

{state.plan}

---

## PHASE 2: Engineering Crew Output

###  Database Engineer Output

```sql
{state.database_code}
```

---

### Backend Engineer Output

```python
{state.backend_code}
```

---

###  Frontend Engineer Output

```tsx
{state.frontend_code}
```

---

## PHASE 3: Judge Crew Output

### Final Validation Report

{state.final_report}

---

## Summary

| Artifact | Status | Size |
|----------|--------|------|
| Plan | {'✅' if state.plan else '❌'} | {len(state.plan)} chars |
| Database Code | {'✅' if state.database_code else '❌'} | {len(state.database_code)} chars |
| Backend Code | {'✅' if state.backend_code else '❌'} | {len(state.backend_code)} chars |
| Frontend Code | {'✅' if state.frontend_code else '❌'} | {len(state.frontend_code)} chars |
| Final Report | {'✅' if state.final_report else '❌'} | {len(state.final_report)} chars |

---

*Log generated by Agentic Software Factory v1.0*
"""
    with open_fn(log_file, "w", encoding="utf-8") as f:
        f.write(log_content)
    return log_file


@pytest.fixture
def sample_state():
    return DevelopmentState(
        id="flow-123",
        status="COMPLETED",
        requirement="Build a todo app",
        plan="Use MVC architecture",
        database_code="CREATE TABLE todos;",
        backend_code="def handler(): pass",
        frontend_code="export const App = () => null;",
        final_report="All checks passed"
    )


def test_save_execution_log_happy_path(tmp_path, sample_state):
    """Validate log file is created with expected content and correct filename."""
    fixed_dt = datetime(2024, 1, 2, 3, 4, 5)
    now_fn = MagicMock(return_value=fixed_dt)

    log_file = save_execution_log(
        sample_state,
        log_dir="logs",
        now_fn=now_fn,
        base_dir=str(tmp_path)
    )

    assert os.path.exists(log_file)
    assert log_file.endswith("execution_log_20240102_030405.md")

    content = open(log_file, "r", encoding="utf-8").read()
    assert "Agentic Software Factory - Execution Log" in content
    assert sample_state.requirement in content
    assert sample_state.plan in content
    assert sample_state.database_code in content
    assert sample_state.backend_code in content
    assert sample_state.frontend_code in content
    assert sample_state.final_report in content
    assert "✅" in content


@pytest.mark.parametrize(
    "plan,db,backend,frontend,report,expected_status",
    [
        ("", "", "", "", "", "❌"),
        ("Plan", "", "", "", "", "✅"),
    ],
)
def test_save_execution_log_edge_cases(tmp_path, plan, db, backend, frontend, report, expected_status):
    """Validate summary status indicators for empty and partial artifacts."""
    state = DevelopmentState(
        id="flow-edge",
        status="IN_PROGRESS",
        requirement="Req",
        plan=plan,
        database_code=db,
        backend_code=backend,
        frontend_code=frontend,
        final_report=report,
    )
    fixed_dt = datetime(2024, 6, 1, 0, 0, 0)
    now_fn = MagicMock(return_value=fixed_dt)

    log_file = save_execution_log(
        state,
        log_dir="logs",
        now_fn=now_fn,
        base_dir=str(tmp_path)
    )

    content = open(log_file, "r", encoding="utf-8").read()
    assert f"| Plan | {expected_status}" in content
    if plan:
        assert f"| Plan | ✅ | {len(plan)} chars |" in content
    else:
        assert f"| Plan | ❌ | {len(plan)} chars |" in content


def test_save_execution_log_raises_on_write_error(sample_state):
    """Validate that write errors propagate as exceptions."""
    def failing_open(*args, **kwargs):
        raise OSError("disk full")

    with pytest.raises(OSError):
        save_execution_log(
            sample_state,
            log_dir="logs",
            now_fn=MagicMock(return_value=datetime(2024, 1, 1, 0, 0, 0)),
            base_dir=os.getcwd(),
            open_fn=failing_open,
            makedirs_fn=MagicMock()
        )