import uuid
from typing import Optional
import pytest
from pydantic import BaseModel, Field, ValidationError
from unittest.mock import MagicMock, Mock


class DevelopmentState(BaseModel):
    """
    Local mock of the DevelopmentState model for testing.
    """
    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for the flow execution"
    )
    requirement: str = Field(
        default="",
        description="The original software requirement or feature request"
    )
    plan: str = Field(
        default="",
        description="Technical specification/plan generated by the Architect"
    )
    database_code: str = Field(
        default="",
        description="SQL schemas, ORM models, and database-related code"
    )
    backend_code: str = Field(
        default="",
        description="API endpoints, business logic, and backend services"
    )
    frontend_code: str = Field(
        default="",
        description="UI components, pages, and frontend logic"
    )
    final_report: str = Field(
        default="",
        description="Final audit report with integrated code and validation results"
    )
    project_name: Optional[str] = Field(
        default=None,
        description="Extracted project name from the requirement"
    )
    status: str = Field(
        default="initialized",
        description="Current status of the development flow"
    )


@pytest.fixture
def fixed_uuid(monkeypatch):
    """Fixture to mock uuid.uuid4 for deterministic id generation."""
    fake_uuid = uuid.UUID("12345678-1234-5678-1234-567812345678")
    mock_uuid4 = MagicMock(return_value=fake_uuid)
    monkeypatch.setattr(uuid, "uuid4", mock_uuid4)
    return mock_uuid4, str(fake_uuid)


def test_default_values_and_uuid_generation(fixed_uuid):
    """Test that default values are correctly set and uuid is generated using mocked dependency."""
    mock_uuid4, expected_id = fixed_uuid
    state = DevelopmentState()
    assert state.id == expected_id
    assert state.requirement == ""
    assert state.plan == ""
    assert state.database_code == ""
    assert state.backend_code == ""
    assert state.frontend_code == ""
    assert state.final_report == ""
    assert state.project_name is None
    assert state.status == "initialized"
    mock_uuid4.assert_called_once()


@pytest.mark.parametrize(
    "requirement, plan, project_name, status",
    [
        ("Build API", "Design endpoints", "ApiProject", "in_progress"),
        ("", "", None, "initialized"),
        ("  ", "Spec", "WhitespaceProj", "planning"),
    ],
)
def test_custom_values_assignment(requirement, plan, project_name, status):
    """Test that provided field values are preserved in the state model."""
    state = DevelopmentState(
        requirement=requirement,
        plan=plan,
        project_name=project_name,
        status=status,
    )
    assert state.requirement == requirement
    assert state.plan == plan
    assert state.project_name == project_name
    assert state.status == status


def test_none_requirement_raises_validation_error():
    """Test that providing None for a required string field raises ValidationError."""
    with pytest.raises(ValidationError):
        DevelopmentState(requirement=None)


def test_external_dependency_mock_usage():
    """Test usage of Mock for a simulated external dependency with state interactions."""
    external_service = Mock()
    state = DevelopmentState(requirement="Create dashboard")
    external_service.process.return_value = f"processed: {state.requirement}"
    result = external_service.process(state.requirement)
    assert result == "processed: Create dashboard"
    external_service.process.assert_called_once_with("Create dashboard")