import sys
import json
from pathlib import Path
import importlib.util
import uuid
import pytest
from pydantic import ValidationError

# TEST PLAN
# 1. test_defaults_and_uuid_generation
# 2. test_unique_ids_for_multiple_instances
# 3. test_custom_values_are_set
# 4. test_optional_project_name_none_and_string
# 5. test_validation_error_for_none_required_fields
# 6. test_schema_contains_descriptions
# 7. test_dict_and_json_serialization
# 8. test_type_coercion_for_status_and_project_name

try:
    from src.code_genereator.state import DevelopmentState
except Exception:
    REPO_ROOT = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(REPO_ROOT))
    spec = importlib.util.spec_from_file_location("state_module", REPO_ROOT / "src/code_genereator/state.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    DevelopmentState = module.DevelopmentState


def test_defaults_and_uuid_generation():
    """Ensure default values are set and id is a valid UUID string."""
    state = DevelopmentState()
    assert isinstance(state.id, str)
    uuid_obj = uuid.UUID(state.id)
    assert str(uuid_obj) == state.id
    assert state.requirement == ""
    assert state.plan == ""
    assert state.database_code == ""
    assert state.backend_code == ""
    assert state.frontend_code == ""
    assert state.final_report == ""
    assert state.project_name is None
    assert state.status == "initialized"


def test_unique_ids_for_multiple_instances():
    """Ensure multiple instances generate unique ids."""
    state1 = DevelopmentState()
    state2 = DevelopmentState()
    assert state1.id != state2.id
    assert uuid.UUID(state1.id)
    assert uuid.UUID(state2.id)


@pytest.mark.parametrize(
    "kwargs",
    [
        {
            "requirement": "Build API",
            "plan": "Plan details",
            "database_code": "CREATE TABLE",
            "backend_code": "def api(): pass",
            "frontend_code": "<div/>",
            "final_report": "All good",
            "project_name": "ProjectX",
            "status": "completed",
        },
        {
            "requirement": "Another",
            "plan": "",
            "database_code": "",
            "backend_code": "",
            "frontend_code": "",
            "final_report": "",
            "project_name": None,
            "status": "in_progress",
        },
    ],
)
def test_custom_values_are_set(kwargs):
    """Verify that provided values are assigned correctly."""
    state = DevelopmentState(**kwargs)
    for key, value in kwargs.items():
        assert getattr(state, key) == value


def test_optional_project_name_none_and_string():
    """Validate project_name accepts None and string values."""
    state_none = DevelopmentState(project_name=None)
    assert state_none.project_name is None
    state_str = DevelopmentState(project_name="MyProject")
    assert state_str.project_name == "MyProject"


def test_validation_error_for_none_required_fields():
    """Ensure ValidationError is raised for None on required str fields."""
    with pytest.raises(ValidationError):
        DevelopmentState(id=None)
    with pytest.raises(ValidationError):
        DevelopmentState(requirement=None)
    with pytest.raises(ValidationError):
        DevelopmentState(status=None)


def test_schema_contains_descriptions():
    """Validate field descriptions are present in schema."""
    schema = DevelopmentState.schema()
    props = schema.get("properties", {})
    assert props["id"]["description"] == "Unique identifier for the flow execution"
    assert props["requirement"]["description"] == "The original software requirement or feature request"
    assert props["plan"]["description"] == "Technical specification/plan generated by the Architect"
    assert props["database_code"]["description"] == "SQL schemas, ORM models, and database-related code"
    assert props["backend_code"]["description"] == "API endpoints, business logic, and backend services"
    assert props["frontend_code"]["description"] == "UI components, pages, and frontend logic"
    assert props["final_report"]["description"] == "Final audit report with integrated code and validation results"
    assert props["project_name"]["description"] == "Extracted project name from the requirement"
    assert props["status"]["description"] == "Current status of the development flow"


def test_dict_and_json_serialization():
    """Ensure dict and json serialization include all fields and values."""
    state = DevelopmentState(
        requirement="Req",
        plan="Plan",
        database_code="DB",
        backend_code="BE",
        frontend_code="FE",
        final_report="Report",
        project_name="Proj",
        status="done",
    )
    data = state.dict()
    assert data["requirement"] == "Req"
    assert data["plan"] == "Plan"
    assert data["database_code"] == "DB"
    assert data["backend_code"] == "BE"
    assert data["frontend_code"] == "FE"
    assert data["final_report"] == "Report"
    assert data["project_name"] == "Proj"
    assert data["status"] == "done"
    json_str = state.json()
    parsed = json.loads(json_str)
    assert parsed["requirement"] == "Req"
    assert parsed["status"] == "done"


def test_type_coercion_for_status_and_project_name():
    """Verify pydantic enforces types for status and project_name."""
    with pytest.raises(ValidationError):
        DevelopmentState(status=123, project_name=456)