import sys
import uuid
from pathlib import Path
import importlib
import importlib.util
from unittest.mock import patch
import pytest
from pydantic import ValidationError

try:
    from code_genereator.state import DevelopmentState
    import code_genereator.state as state_module
except Exception:
    REPO_ROOT = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(REPO_ROOT))
    spec = importlib.util.spec_from_file_location("state_module", REPO_ROOT / "src/code_genereator/state.py")
    state_module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(state_module)
    DevelopmentState = state_module.DevelopmentState


def test_defaults_and_types():
    """Validate that default values are correctly assigned and types are valid."""
    state = DevelopmentState()
    assert state.requirement == ""
    assert state.plan == ""
    assert state.database_code == ""
    assert state.backend_code == ""
    assert state.frontend_code == ""
    assert state.final_report == ""
    assert state.project_name is None
    assert state.status == "initialized"
    assert isinstance(state.id, str)
    uuid.UUID(state.id)
    data = state.dict()
    expected_keys = {
        "id",
        "requirement",
        "plan",
        "database_code",
        "backend_code",
        "frontend_code",
        "final_report",
        "project_name",
        "status",
    }
    assert set(data.keys()) == expected_keys


def test_custom_values_preserved():
    """Ensure explicitly provided values are preserved in the model."""
    state = DevelopmentState(
        id="custom-id",
        requirement="req",
        plan="plan",
        database_code="db",
        backend_code="be",
        frontend_code="fe",
        final_report="report",
        project_name="proj",
        status="done",
    )
    assert state.id == "custom-id"
    assert state.requirement == "req"
    assert state.plan == "plan"
    assert state.database_code == "db"
    assert state.backend_code == "be"
    assert state.frontend_code == "fe"
    assert state.final_report == "report"
    assert state.project_name == "proj"
    assert state.status == "done"


def test_uuid_default_factory_called():
    """Confirm that the uuid4 default factory is used for the id field."""
    fixed_uuid = uuid.UUID("12345678-1234-5678-1234-567812345678")
    with patch.object(state_module.uuid, "uuid4", return_value=fixed_uuid) as mock_uuid4:
        state = DevelopmentState()
        assert state.id == str(fixed_uuid)
        mock_uuid4.assert_called_once()


@pytest.mark.parametrize(
    "field_name",
    [
        "id",
        "requirement",
        "plan",
        "database_code",
        "backend_code",
        "frontend_code",
        "final_report",
        "status",
    ],
)
def test_none_for_required_fields_raises(field_name):
    """Validate that None is not accepted for required string fields."""
    payload = {field_name: None}
    with pytest.raises(ValidationError):
        DevelopmentState(**payload)


def test_optional_project_name_accepts_none_and_rejects_non_string():
    """Ensure project_name accepts None and rejects non-string types."""
    state_none = DevelopmentState(project_name=None)
    assert state_none.project_name is None
    with pytest.raises(ValidationError):
        DevelopmentState(project_name=123)


def test_schema_contains_descriptions():
    """Verify schema includes descriptions for fields to cover schema generation."""
    schema = DevelopmentState.schema()
    props = schema.get("properties", {})
    assert props["id"]["description"] == "Unique identifier for the flow execution"
    assert props["requirement"]["description"] == "The original software requirement or feature request"
    assert props["plan"]["description"] == "Technical specification/plan generated by the Architect"
    assert props["database_code"]["description"] == "SQL schemas, ORM models, and database-related code"
    assert props["backend_code"]["description"] == "API endpoints, business logic, and backend services"
    assert props["frontend_code"]["description"] == "UI components, pages, and frontend logic"
    assert props["final_report"]["description"] == "Final audit report with integrated code and validation results"
    assert props["project_name"]["description"] == "Extracted project name from the requirement"
    assert props["status"]["description"] == "Current status of the development flow"


def test_multiple_instances_have_unique_ids():
    """Create two instances to ensure ids are unique and valid UUID strings."""
    state1 = DevelopmentState()
    state2 = DevelopmentState()
    assert state1.id != state2.id
    uuid.UUID(state1.id)
    uuid.UUID(state2.id)