"""
Development State Model for the Agentic Software Factory.

This module defines the Pydantic state that flows through the entire
software development pipeline, carrying artifacts from planning through
final code generation.
"""

import uuid
from pydantic import BaseModel, Field
from typing import Optional


class DevelopmentState(BaseModel):
    """
    State model for the software development flow.

    This state is passed between crews and accumulates artifacts
    as the development progresses through planning, engineering,
    and final validation phases.
    """

    # Required id field for CrewAI Flow
    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for the flow execution"
    )

    # Initial requirement from user
    requirement: str = Field(
        default="",
        description="The original software requirement or feature request"
    )
    
    # Planning phase output
    plan: str = Field(
        default="",
        description="Technical specification/plan generated by the Architect"
    )
    
    # Engineering phase outputs
    database_code: str = Field(
        default="",
        description="SQL schemas, ORM models, and database-related code"
    )
    
    backend_code: str = Field(
        default="",
        description="API endpoints, business logic, and backend services"
    )
    
    frontend_code: str = Field(
        default="",
        description="UI components, pages, and frontend logic"
    )
    
    # Final validation output
    final_report: str = Field(
        default="",
        description="Final audit report with integrated code and validation results"
    )
    
    # Metadata
    project_name: Optional[str] = Field(
        default=None,
        description="Extracted project name from the requirement"
    )
    
    status: str = Field(
        default="initialized",
        description="Current status of the development flow"
    )

