"""
DeepResearchTool for performing structured research in code generation workflow.

This tool conducts comprehensive analysis of software requirements through
a structured research process, producing detailed Markdown research plans.
"""

import os
from typing import Type

from crewai.tools import BaseTool
from pydantic import BaseModel, Field


class DeepResearchToolInput(BaseModel):
    """Input schema for DeepResearchTool."""
    
    requirement: str = Field(
        ...,
        description="The software requirement or project specification to research"
    )
    research_scope: str = Field(
        ...,
        description="The scope and focus areas for the research (e.g., 'backend architecture', 'full-stack web app', 'database design')"
    )


class DeepResearchTool(BaseTool):
    """
    Tool for performing deep research and analysis of software requirements.
    
    Conducts structured research through multiple phases: context gathering,
    iterative analysis, gap identification, and synthesis of findings into
    a comprehensive Markdown research plan.
    """
    
    name: str = "deep_research_tool"
    description: str = (
        "Performs deep research and analysis of software requirements through a structured process. "
        "Gathers context, analyzes technical approaches, identifies risks and trade-offs, "
        "and synthesizes findings into a comprehensive Markdown research plan. "
        "Use this before code generation to ensure thorough understanding and planning."
    )
    args_schema: Type[BaseModel] = DeepResearchToolInput
    
    def _run(self, requirement: str, research_scope: str) -> str:
        """
        Perform deep research on the given requirement and generate a structured research plan.
        
        Args:
            requirement: The software requirement to research
            research_scope: The scope and focus areas for research
            
        Returns:
            Comprehensive Markdown research plan or error message
        """
        try:
            research_plan = self._conduct_structured_research(requirement, research_scope)
            return research_plan
            
        except Exception as e:
            return f"Error during research process: {str(e)}"
    
    def _conduct_structured_research(self, requirement: str, research_scope: str) -> str:
        """
        Conduct the structured research process and generate Markdown output.
        
        Args:
            requirement: The software requirement to analyze
            research_scope: The research scope and focus areas
            
        Returns:
            Formatted Markdown research plan
        """
        problem_analysis = self._analyze_problem(requirement)
        technical_approach = self._determine_technical_approach(requirement, research_scope)
        design_decisions = self._identify_design_decisions(requirement, research_scope)
        trade_offs = self._analyze_trade_offs(requirement, research_scope)
        risks = self._identify_risks(requirement, research_scope)
        roadmap = self._create_implementation_roadmap(requirement, research_scope)
        
        markdown_content = f"""# Deep Research Plan

## Problem Analysis

{problem_analysis}

## Technical Approach

{technical_approach}

## Design Decisions

{design_decisions}

## Trade-offs

{trade_offs}

## Risks

{risks}

## Implementation Roadmap

{roadmap}

---
*Generated by DeepResearchTool*
"""
        
        return markdown_content
    
    def _analyze_problem(self, requirement: str) -> str:
        """Analyze and break down the core problem from the requirement."""
        analysis_sections = []
        
        analysis_sections.append("### Core Problem Statement")
        analysis_sections.append(f"The primary challenge is to implement: {requirement}")
        
        analysis_sections.append("\n### Key Requirements Breakdown")
        req_words = requirement.lower().split()
        
        if any(word in req_words for word in ['web', 'website', 'frontend', 'ui']):
            analysis_sections.append("- **Frontend Requirements**: User interface and experience components")
        
        if any(word in req_words for word in ['api', 'backend', 'server', 'database']):
            analysis_sections.append("- **Backend Requirements**: Server-side logic and data management")
        
        if any(word in req_words for word in ['auth', 'login', 'user', 'account']):
            analysis_sections.append("- **Authentication**: User management and security")
        
        if any(word in req_words for word in ['data', 'store', 'save', 'database']):
            analysis_sections.append("- **Data Management**: Storage, retrieval, and persistence")
        
        analysis_sections.append("\n### Success Criteria")
        analysis_sections.append("- Functional implementation meeting all specified requirements")
        analysis_sections.append("- Scalable and maintainable code architecture")
        analysis_sections.append("- Proper error handling and validation")
        analysis_sections.append("- Clear documentation and testing coverage")
        
        return "\n".join(analysis_sections)
    
    def _determine_technical_approach(self, requirement: str, research_scope: str) -> str:
        """Determine the recommended technical approach and architecture."""
        approach_sections = []
        
        approach_sections.append("### Recommended Technology Stack")
        
        req_lower = requirement.lower()
        scope_lower = research_scope.lower()
        
        if 'web' in req_lower or 'frontend' in scope_lower:
            approach_sections.append("**Frontend:**")
            if 'react' in req_lower or 'react' in scope_lower:
                approach_sections.append("- React.js with TypeScript for type safety")
                approach_sections.append("- React Router for navigation")
                approach_sections.append("- Axios for API communication")
            else:
                approach_sections.append("- Modern JavaScript framework (React/Vue/Angular)")
                approach_sections.append("- Component-based architecture")
                approach_sections.append("- State management solution")
        
        if 'backend' in scope_lower or 'api' in req_lower:
            approach_sections.append("\n**Backend:**")
            if 'python' in req_lower or 'django' in req_lower or 'flask' in req_lower:
                approach_sections.append("- Python with Django/Flask framework")
                approach_sections.append("- Django REST Framework for API development")
                approach_sections.append("- SQLAlchemy for database ORM")
            elif 'node' in req_lower or 'express' in req_lower:
                approach_sections.append("- Node.js with Express.js framework")
                approach_sections.append("- TypeScript for type safety")
                approach_sections.append("- Prisma or TypeORM for database management")
            else:
                approach_sections.append("- RESTful API architecture")
                approach_sections.append("- MVC pattern implementation")
                approach_sections.append("- Middleware for authentication and validation")
        
        if 'database' in req_lower or 'data' in req_lower:
            approach_sections.append("\n**Database:**")
            if 'nosql' in req_lower or 'mongo' in req_lower:
                approach_sections.append("- MongoDB for document-based storage")
                approach_sections.append("- Mongoose for object modeling")
            else:
                approach_sections.append("- PostgreSQL for relational data")
                approach_sections.append("- Proper indexing and constraints")
                approach_sections.append("- Migration system for schema changes")
        
        approach_sections.append("\n### Architecture Patterns")
        approach_sections.append("- **Separation of Concerns**: Clear separation between layers")
        approach_sections.append("- **Repository Pattern**: Abstract data access logic")
        approach_sections.append("- **Service Layer**: Business logic encapsulation")
        approach_sections.append("- **Error Handling**: Centralized error management")
        
        return "\n".join(approach_sections)
    
    def _identify_design_decisions(self, requirement: str, research_scope: str) -> str:
        """Identify key design decisions and their rationale."""
        decisions_sections = []
        
        decisions_sections.append("### Key Design Choices")
        
        decisions_sections.append("**1. Architecture Pattern**")
        if 'microservice' in requirement.lower():
            decisions_sections.append("- *Decision*: Microservices architecture")
            decisions_sections.append("- *Rationale*: Scalability and service independence")
        else:
            decisions_sections.append("- *Decision*: Monolithic architecture with modular design")
            decisions_sections.append("- *Rationale*: Simplicity and faster initial development")
        
        decisions_sections.append("\n**2. Data Storage Strategy**")
        if 'real-time' in requirement.lower() or 'chat' in requirement.lower():
            decisions_sections.append("- *Decision*: Hybrid storage with caching layer")
            decisions_sections.append("- *Rationale*: Performance optimization for real-time features")
        else:
            decisions_sections.append("- *Decision*: Traditional relational database")
            decisions_sections.append("- *Rationale*: ACID compliance and data consistency")
        
        decisions_sections.append("\n**3. Authentication Strategy**")
        if 'auth' in requirement.lower() or 'login' in requirement.lower():
            decisions_sections.append("- *Decision*: JWT-based authentication")
            decisions_sections.append("- *Rationale*: Stateless and scalable authentication")
        else:
            decisions_sections.append("- *Decision*: Session-based authentication")
            decisions_sections.append("- *Rationale*: Simple implementation and security")
        
        decisions_sections.append("\n**4. API Design**")
        decisions_sections.append("- *Decision*: RESTful API with OpenAPI documentation")
        decisions_sections.append("- *Rationale*: Industry standard and excellent tooling support")
        
        decisions_sections.append("\n**5. Testing Strategy**")
        decisions_sections.append("- *Decision*: Multi-layer testing approach")
        decisions_sections.append("- *Rationale*: Unit tests, integration tests, and E2E coverage")
        
        return "\n".join(decisions_sections)
    
    def _analyze_trade_offs(self, requirement: str, research_scope: str) -> str:
        """Analyze trade-offs of different approaches."""
        tradeoffs_sections = []
        
        tradeoffs_sections.append("### Technology Trade-offs")
        
        tradeoffs_sections.append("**Framework Selection**")
        tradeoffs_sections.append("*Pros:*")
        tradeoffs_sections.append("- Rapid development with established patterns")
        tradeoffs_sections.append("- Large community and ecosystem support")
        tradeoffs_sections.append("- Built-in security and best practices")
        tradeoffs_sections.append("*Cons:*")
        tradeoffs_sections.append("- Learning curve for team members")
        tradeoffs_sections.append("- Framework lock-in and dependency management")
        tradeoffs_sections.append("- Potential performance overhead")
        
        tradeoffs_sections.append("\n**Database Choice**")
        tradeoffs_sections.append("*Relational Database Pros:*")
        tradeoffs_sections.append("- ACID compliance and data consistency")
        tradeoffs_sections.append("- Mature tooling and optimization")
        tradeoffs_sections.append("- Complex query capabilities")
        tradeoffs_sections.append("*Relational Database Cons:*")
        tradeoffs_sections.append("- Rigid schema requirements")
        tradeoffs_sections.append("- Horizontal scaling challenges")
        tradeoffs_sections.append("- Performance bottlenecks with large datasets")
        
        tradeoffs_sections.append("\n**Architecture Approach**")
        tradeoffs_sections.append("*Monolithic Pros:*")
        tradeoffs_sections.append("- Simpler deployment and debugging")
        tradeoffs_sections.append("- Easier transaction management")
        tradeoffs_sections.append("- Lower operational complexity")
        tradeoffs_sections.append("*Monolithic Cons:*")
        tradeoffs_sections.append("- Scaling limitations")
        tradeoffs_sections.append("- Technology stack lock-in")
        tradeoffs_sections.append("- Potential single point of failure")
        
        return "\n".join(tradeoffs_sections)
    
    def _identify_risks(self, requirement: str, research_scope: str) -> str:
        """Identify potential risks and mitigation strategies."""
        risks_sections = []
        
        risks_sections.append("### Technical Risks")
        
        risks_sections.append("**1. Scalability Concerns**")
        risks_sections.append("- *Risk*: Performance degradation under high load")
        risks_sections.append("- *Mitigation*: Implement caching, database optimization, and load testing")
        risks_sections.append("- *Monitoring*: Set up performance metrics and alerting")
        
        risks_sections.append("\n**2. Security Vulnerabilities**")
        risks_sections.append("- *Risk*: Data breaches and unauthorized access")
        risks_sections.append("- *Mitigation*: Input validation, authentication, and security audits")
        risks_sections.append("- *Monitoring*: Security scanning and penetration testing")
        
        risks_sections.append("\n**3. Data Integrity Issues**")
        risks_sections.append("- *Risk*: Data corruption or loss")
        risks_sections.append("- *Mitigation*: Regular backups, transaction management, and validation")
        risks_sections.append("- *Monitoring*: Data consistency checks and backup verification")
        
        risks_sections.append("\n**4. Integration Complexity**")
        risks_sections.append("- *Risk*: Third-party service dependencies and API changes")
        risks_sections.append("- *Mitigation*: Abstraction layers, fallback mechanisms, and versioning")
        risks_sections.append("- *Monitoring*: Service health checks and dependency tracking")
        
        risks_sections.append("\n**5. Deployment and Operations**")
        risks_sections.append("- *Risk*: Deployment failures and environment inconsistencies")
        risks_sections.append("- *Mitigation*: CI/CD pipelines, containerization, and staging environments")
        risks_sections.append("- *Monitoring*: Deployment tracking and rollback procedures")
        
        return "\n".join(risks_sections)
    
    def _create_implementation_roadmap(self, requirement: str, research_scope: str) -> str:
        """Create a detailed implementation roadmap."""
        roadmap_sections = []
        
        roadmap_sections.append("### Phase 1: Foundation Setup (Week 1-2)")
        roadmap_sections.append("**Infrastructure & Environment**")
        roadmap_sections.append("- [ ] Set up development environment and tooling")
        roadmap_sections.append("- [ ] Initialize project structure and repository")
        roadmap_sections.append("- [ ] Configure CI/CD pipeline basics")
        roadmap_sections.append("- [ ] Set up database and basic schema")
        
        roadmap_sections.append("\n**Core Architecture**")
        roadmap_sections.append("- [ ] Implement basic project structure")
        roadmap_sections.append("- [ ] Set up configuration management")
        roadmap_sections.append("- [ ] Create base models and entities")
        roadmap_sections.append("- [ ] Implement error handling framework")
        
        roadmap_sections.append("\n### Phase 2: Core Features (Week 3-5)")
        roadmap_sections.append("**Backend Development**")
        roadmap_sections.append("- [ ] Implement core business logic")
        roadmap_sections.append("- [ ] Create API endpoints and routing")
        roadmap_sections.append("- [ ] Add authentication and authorization")
        roadmap_sections.append("- [ ] Implement data validation and sanitization")
        
        roadmap_sections.append("\n**Database Layer**")
        roadmap_sections.append("- [ ] Complete database schema implementation")
        roadmap_sections.append("- [ ] Add indexes and performance optimizations")
        roadmap_sections.append("- [ ] Implement data migration system")
        roadmap_sections.append("- [ ] Create seed data and fixtures")
        
        roadmap_sections.append("\n### Phase 3: Frontend & Integration (Week 6-8)")
        roadmap_sections.append("**Frontend Development**")
        if 'web' in requirement.lower() or 'frontend' in research_scope.lower():
            roadmap_sections.append("- [ ] Create component library and design system")
            roadmap_sections.append("- [ ] Implement main user interface components")
            roadmap_sections.append("- [ ] Add state management and routing")
            roadmap_sections.append("- [ ] Integrate with backend APIs")
        else:
            roadmap_sections.append("- [ ] Create API documentation and examples")
            roadmap_sections.append("- [ ] Implement client SDKs if needed")
            roadmap_sections.append("- [ ] Add API versioning and backwards compatibility")
        
        roadmap_sections.append("\n**Integration & Testing**")
        roadmap_sections.append("- [ ] Write comprehensive unit tests")
        roadmap_sections.append("- [ ] Implement integration test suite")
        roadmap_sections.append("- [ ] Add end-to-end testing scenarios")
        roadmap_sections.append("- [ ] Performance testing and optimization")
        
        roadmap_sections.append("\n### Phase 4: Polish & Deployment (Week 9-10)")
        roadmap_sections.append("**Quality Assurance**")
        roadmap_sections.append("- [ ] Code review and refactoring")
        roadmap_sections.append("- [ ] Security audit and vulnerability assessment")
        roadmap_sections.append("- [ ] Performance profiling and optimization")
        roadmap_sections.append("- [ ] Documentation completion")
        
        roadmap_sections.append("\n**Deployment & Operations**")
        roadmap_sections.append("- [ ] Production environment setup")
        roadmap_sections.append("- [ ] Monitoring and logging implementation")
        roadmap_sections.append("- [ ] Backup and disaster recovery procedures")
        roadmap_sections.append("- [ ] User acceptance testing and feedback")
        
        roadmap_sections.append("\n### Success Metrics")
        roadmap_sections.append("- **Functionality**: All requirements implemented and tested")
        roadmap_sections.append("- **Performance**: Response times under acceptable thresholds")
        roadmap_sections.append("- **Security**: No critical vulnerabilities identified")
        roadmap_sections.append("- **Maintainability**: Code coverage above 80% and documentation complete")
        
        return "\n".join(roadmap_sections)
